.TH siduxcc 1 "Januar  1, 2009"
.SH NAME
sidux-hermes \- upgrade sentinel
.SH SYNOPSIS
\fBsidux-hermes\fR \fI<options>\fR
.SH DESCRIPTION
\fBsidux-hermes\fP shows the status of the Debian sid repository.
.br
.SH OPTIONS
.TP
.B \-s, \--status
show the status of the debian sid repository
.TP
.B \-ck, \--current-kernel
show the version of the current kernel
.TP
.B \-nk, \--newest-kernel
show the version of the newest kernel
.TP
.B \-up, \--upgradable-packagesl
show the upgradable package
.TP
.B \-h, \--help
print help screen
.br
.SH AUTHOR
sidux-hermes was written by Fabian Wuertz <xadras@sidux.com>.
.PP
This manual page was written by Fabian Wuertz <xadras@sidux.com>.